services:
  - type: web
    name: model-powerlaw
    runtime: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free

